site_name: pythonSeed
site_description: Project seed in Python
repo_url: https://github.com/breinergonza/pythonSeed
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/breinergonza">breinergonza</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
